/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuruRouteImport } from './routes/guru'
import { Route as InputNilaiRouteImport } from './routes/input-nilai'
import { Route as KelasRouteImport } from './routes/kelas'
import { Route as LogAktivitasRouteImport } from './routes/log-aktivitas'
import { Route as MataPelajaranRouteImport } from './routes/mata-pelajaran'
import { Route as RaporRouteImport } from './routes/rapor'
import { Route as RekapNilaiRouteImport } from './routes/rekap-nilai'
import { Route as SiswaRouteImport } from './routes/siswa'
import { Route as TahunAjaranRouteImport } from './routes/tahun-ajaran'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuruRoute = GuruRouteImport.update({
  id: '/guru',
  path: '/guru',
  getParentRoute: () => rootRouteImport,
} as any)
const InputNilaiRoute = InputNilaiRouteImport.update({
  id: '/input-nilai',
  path: '/input-nilai',
  getParentRoute: () => rootRouteImport,
} as any)
const KelasRoute = KelasRouteImport.update({
  id: '/kelas',
  path: '/kelas',
  getParentRoute: () => rootRouteImport,
} as any)
const LogAktivitasRoute = LogAktivitasRouteImport.update({
  id: '/log-aktivitas',
  path: '/log-aktivitas',
  getParentRoute: () => rootRouteImport,
} as any)
const MataPelajaranRoute = MataPelajaranRouteImport.update({
  id: '/mata-pelajaran',
  path: '/mata-pelajaran',
  getParentRoute: () => rootRouteImport,
} as any)
const RaporRoute = RaporRouteImport.update({
  id: '/rapor',
  path: '/rapor',
  getParentRoute: () => rootRouteImport,
} as any)
const RekapNilaiRoute = RekapNilaiRouteImport.update({
  id: '/rekap-nilai',
  path: '/rekap-nilai',
  getParentRoute: () => rootRouteImport,
} as any)
const SiswaRoute = SiswaRouteImport.update({
  id: '/siswa',
  path: '/siswa',
  getParentRoute: () => rootRouteImport,
} as any)
const TahunAjaranRoute = TahunAjaranRouteImport.update({
  id: '/tahun-ajaran',
  path: '/tahun-ajaran',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/guru': typeof GuruRoute
  '/input-nilai': typeof InputNilaiRoute
  '/kelas': typeof KelasRoute
  '/log-aktivitas': typeof LogAktivitasRoute
  '/mata-pelajaran': typeof MataPelajaranRoute
  '/rapor': typeof RaporRoute
  '/rekap-nilai': typeof RekapNilaiRoute
  '/siswa': typeof SiswaRoute
  '/tahun-ajaran': typeof TahunAjaranRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/guru': typeof GuruRoute
  '/input-nilai': typeof InputNilaiRoute
  '/kelas': typeof KelasRoute
  '/log-aktivitas': typeof LogAktivitasRoute
  '/mata-pelajaran': typeof MataPelajaranRoute
  '/rapor': typeof RaporRoute
  '/rekap-nilai': typeof RekapNilaiRoute
  '/siswa': typeof SiswaRoute
  '/tahun-ajaran': typeof TahunAjaranRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/guru': typeof GuruRoute
  '/input-nilai': typeof InputNilaiRoute
  '/kelas': typeof KelasRoute
  '/log-aktivitas': typeof LogAktivitasRoute
  '/mata-pelajaran': typeof MataPelajaranRoute
  '/rapor': typeof RaporRoute
  '/rekap-nilai': typeof RekapNilaiRoute
  '/siswa': typeof SiswaRoute
  '/tahun-ajaran': typeof TahunAjaranRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/guru'
    | '/input-nilai'
    | '/kelas'
    | '/log-aktivitas'
    | '/mata-pelajaran'
    | '/rapor'
    | '/rekap-nilai'
    | '/siswa'
    | '/tahun-ajaran'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/guru'
    | '/input-nilai'
    | '/kelas'
    | '/log-aktivitas'
    | '/mata-pelajaran'
    | '/rapor'
    | '/rekap-nilai'
    | '/siswa'
    | '/tahun-ajaran'
  id:
    | '__root__'
    | '/'
    | '/guru'
    | '/input-nilai'
    | '/kelas'
    | '/log-aktivitas'
    | '/mata-pelajaran'
    | '/rapor'
    | '/rekap-nilai'
    | '/siswa'
    | '/tahun-ajaran'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuruRoute: typeof GuruRoute
  InputNilaiRoute: typeof InputNilaiRoute
  KelasRoute: typeof KelasRoute
  LogAktivitasRoute: typeof LogAktivitasRoute
  MataPelajaranRoute: typeof MataPelajaranRoute
  RaporRoute: typeof RaporRoute
  RekapNilaiRoute: typeof RekapNilaiRoute
  SiswaRoute: typeof SiswaRoute
  TahunAjaranRoute: typeof TahunAjaranRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guru': {
      id: '/guru'
      path: '/guru'
      fullPath: '/guru'
      preLoaderRoute: typeof GuruRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/input-nilai': {
      id: '/input-nilai'
      path: '/input-nilai'
      fullPath: '/input-nilai'
      preLoaderRoute: typeof InputNilaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kelas': {
      id: '/kelas'
      path: '/kelas'
      fullPath: '/kelas'
      preLoaderRoute: typeof KelasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log-aktivitas': {
      id: '/log-aktivitas'
      path: '/log-aktivitas'
      fullPath: '/log-aktivitas'
      preLoaderRoute: typeof LogAktivitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mata-pelajaran': {
      id: '/mata-pelajaran'
      path: '/mata-pelajaran'
      fullPath: '/mata-pelajaran'
      preLoaderRoute: typeof MataPelajaranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapor': {
      id: '/rapor'
      path: '/rapor'
      fullPath: '/rapor'
      preLoaderRoute: typeof RaporRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rekap-nilai': {
      id: '/rekap-nilai'
      path: '/rekap-nilai'
      fullPath: '/rekap-nilai'
      preLoaderRoute: typeof RekapNilaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/siswa': {
      id: '/siswa'
      path: '/siswa'
      fullPath: '/siswa'
      preLoaderRoute: typeof SiswaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tahun-ajaran': {
      id: '/tahun-ajaran'
      path: '/tahun-ajaran'
      fullPath: '/tahun-ajaran'
      preLoaderRoute: typeof TahunAjaranRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuruRoute: GuruRoute,
  InputNilaiRoute: InputNilaiRoute,
  KelasRoute: KelasRoute,
  LogAktivitasRoute: LogAktivitasRoute,
  MataPelajaranRoute: MataPelajaranRoute,
  RaporRoute: RaporRoute,
  RekapNilaiRoute: RekapNilaiRoute,
  SiswaRoute: SiswaRoute,
  TahunAjaranRoute: TahunAjaranRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
